---
- name: Install containerd
  ansible.builtin.apt:
    name: containerd
    state: present
    update_cache: true

- name: Ensure containerd config directory exists
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Write /etc/containerd/config.toml (systemd cgroup)
  ansible.builtin.copy:
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'
    content: |
      version = 2

      [plugins]
        [plugins."io.containerd.grpc.v1.cri".containerd]
          snapshotter = "overlayfs"
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
            runtime_type = "io.containerd.runc.v2"
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
              SystemdCgroup = true

- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted
    enabled: true
